// Translations of the existing curated references; durations and conditions are unchanged.
export const STORAGE_EN = {
  '一枚小小的圆，藏着早餐与家常菜的许多可能。': 'A small egg holds plenty of possibilities for breakfast and home cooking.',
  '传统食养资料常记为性平': 'Traditionally described as neutral in food culture',
  '传统食养资料常记为性温': 'Traditionally described as warming in food culture',
  '传统食养资料常记为性凉': 'Traditionally described as cooling in food culture',
  '传统食养资料常记为性微寒': 'Traditionally described as slightly cold in food culture',
  '传统食养资料常记为性寒': 'Traditionally described as cold in food culture',
  '近期可做番茄炒蛋、蒸蛋或溏心蛋。': 'Ideas: tomato scrambled eggs, steamed eggs or soft-boiled eggs.',
  '以包装日期为准': 'Follow the package date', '整颗带壳鸡蛋不建议冷冻': 'Do not freeze whole eggs in their shells', '新加坡气候下建议冷藏': 'Refrigeration is recommended in Singapore’s climate',
  '清晨的一杯白，是一天最轻柔的开场。': 'A glass of milk makes a gentle start to the morning.',
  '可做奶香燕麦、炖蛋或白酱。': 'Ideas: milky oats, egg custard or white sauce.',
  '开封后按包装说明尽快饮用': 'Once opened, use promptly according to the label', '口感与质地可能明显变化': 'Flavour and texture may change noticeably', '鲜奶需冷藏；常温奶未开封例外': 'Fresh milk needs refrigeration; unopened shelf-stable milk is an exception',
  '微酸的乳香，适合给忙碌日子留一点从容。': 'A gentle dairy tang for a calm moment in a busy day.',
  '可拌水果、做隔夜燕麦或酸奶酱。': 'Ideas: fruit yogurt, overnight oats or yogurt dressing.',
  '以包装日期与开封说明为准': 'Follow the package date and instructions after opening', '解冻后易分层': 'May separate after thawing', '需保持冷链': 'Maintain the cold chain',
  '清爽利落的肉香，最适合接住不同香料的性格。': 'Mild meat flavour pairs well with a wide range of spices.',
  '可做香煎鸡胸、咖喱鸡或手撕鸡。': 'Ideas: pan-seared chicken breast, chicken curry or shredded chicken.',
  '未开封包装日期优先；生鲜禽肉建议尽快烹调': 'Follow the sealed-package date; cook fresh poultry promptly',
  '去除多余空气、分成一餐份量密封；45 天是偏保守的风味建议，不是安全上限': 'Remove air and seal in meal-sized portions. The 45-day reminder is conservative flavour guidance, not a safety limit.',
  '禽肉分割件的官方冷冻品质参考可更长；本产品为家庭口感设更短建议期': 'Official frozen-quality guidance for poultry cuts may be longer; this app uses a shorter reminder for home eating quality.',
  '生鲜、分装密封、−18°C 或以下': 'Fresh, sealed in portions, at −18°C or below', '生鲜肉不可常温久放': 'Do not leave raw meat at room temperature for extended periods',
  '细碎的纹理更容易接住酱汁，也更需要把握新鲜。': 'Ground meat takes up sauces well and needs particular attention to freshness.',
  '可做番茄牛肉碎、肉酱面或汉堡排。': 'Ideas: tomato ground beef, meat-sauce pasta or burger patties.',
  '肉碎表面积更大，建议优先按包装日期并在 1–2 天内使用': 'Ground meat has more exposed surface. Follow the package date and aim to use within 1–2 days.',
  '冷藏 1–2 天': 'Refrigerated: 1–2 days', '冷藏 3–5 天': 'Refrigerated: 3–5 days',
  '压薄、排气、按一餐份量密封；建议 30 天内吃完以保持较好色泽与风味': 'Flatten, remove air and seal meal-sized portions. Use within 30 days for better colour and flavour.',
  '官方最佳品质参考约 3–4 个月；本产品默认提醒更保守': 'Official best-quality reference: about 3–4 months. This app’s default reminder is more conservative.',
  '生鲜肉碎、密封、−18°C 或以下': 'Fresh ground meat, sealed, at −18°C or below',
  '火候一到，肉香便有了沉稳而丰厚的底色。': 'The right heat brings out a deep, rich meat flavour.',
  '可做黑椒牛肉、番茄炖牛肉或牛肉炒饭。': 'Ideas: black-pepper beef, tomato beef stew or beef fried rice.',
  '整块牛肉与牛排建议按包装日期，并在 3–5 天内烹调': 'Follow package dates for whole beef cuts and steaks; aim to cook within 3–5 days.',
  '吸干表面、排气密封并标记日期；45 天是 FreshLoop 偏保守的风味提醒': 'Pat dry, remove air, seal and date. FreshLoop uses a conservative 45-day flavour reminder.',
  '牛排及整块牛肉官方最佳品质参考约 6–12 个月': 'Official best-quality reference for steaks and whole beef cuts: about 6–12 months',
  '整块生牛肉、密封、−18°C 或以下': 'Whole raw beef cuts, sealed, at −18°C or below',
  '水里的鲜味来到餐桌，总带着一点潮汐的气息。': 'Fresh flavours from the water bring a taste of the sea to the table.',
  '不同鱼类传统属性不一': 'Traditional food-culture descriptions vary by fish species', '可清蒸、香煎或做味噌汤。': 'Ideas: steamed fish, pan-fried fish or miso soup.',
  '海鲜建议尽快烹调': 'Cook seafood promptly', '擦干分装并密封': 'Pat dry, portion and seal', '不可常温久放': 'Do not keep at room temperature for extended periods',
  '清白一方，最能把汤汁与香气慢慢收进心里。': 'Mild tofu readily absorbs the flavours of sauces and broth.',
  '可做麻婆豆腐、豆腐汤或香煎豆腐。': 'Ideas: mapo tofu, tofu soup or pan-fried tofu.',
  '开封后换净水并尽快用完': 'After opening, change to clean water and use promptly', '会形成蜂窝口感': 'Freezing creates a spongy texture', '鲜豆腐需冷藏': 'Fresh tofu needs refrigeration',
  '一把青叶，是餐桌上最轻盈的一笔春色。': 'A handful of green leaves brings freshness to the table.',
  '近期可做蒜蓉菠菜、菠菜蛋汤或拌面。': 'Ideas: garlic spinach, spinach egg soup or noodles.',
  '不预洗、吸湿包裹后冷藏': 'Do not prewash; wrap in absorbent material and refrigerate',
  '仅在焯水、冷却并挤干后启用；建议 30 天内用于熟食': 'Only after blanching, cooling and squeezing dry. Use in cooked dishes within 30 days.',
  '处理方式会显著改变品质': 'Preparation substantially affects quality', '焯水、冷却、挤干、密封': 'Blanch, cool, squeeze dry and seal', '当天食用': 'Eat the same day',
  '细密的花球像一片微缩森林，脆嫩里藏着清甜。': 'Tender-crisp florets bring a naturally mild sweetness.',
  '可清炒、焗烤或搭配鸡胸肉。': 'Ideas: stir-fry, bake or serve with chicken breast.',
  '保持干燥并留出透气空间': 'Keep dry and allow airflow', '仅在焯水、彻底冷却并沥干后启用': 'Only after blanching, cooling completely and draining',
  '切小朵、焯水、冷却、沥干、密封': 'Cut into florets, blanch, cool, drain and seal', '尽量当天使用': 'Preferably use the same day',
  '红得明亮，也酸甜得坦率，最会让一锅菜有生气。': 'Bright colour and sweet acidity bring a dish to life.',
  '可做番茄炒蛋、番茄炖牛肉或意面酱。': 'Ideas: tomato scrambled eggs, beef stew or pasta sauce.',
  '完全成熟后冷藏，食用前回温风味更好': 'Refrigerate when fully ripe; bring to room temperature before eating for better flavour',
  '切块或煮成酱后密封；解冻后只建议用于熟食': 'Dice or cook into sauce, then seal. Use only in cooked dishes after thawing.',
  '冷冻会破坏鲜食质地': 'Freezing affects the texture for fresh eating', '切块或制酱、密封': 'Dice or make sauce, then seal', '未熟时可常温放至转红': 'Unripe tomatoes may ripen at room temperature until red',
  '热带的甜意弯成一轮小月，熟得刚好时最温柔。': 'Naturally sweet and soft when just ripe.',
  '可做燕麦杯、奶昔或香蕉煎饼。': 'Ideas: oat cups, smoothies or banana pancakes.',
  '成熟后冷藏，表皮变黑不等于果肉变坏': 'Refrigerate once ripe; a dark peel alone does not mean the flesh is spoiled',
  '去皮切段，适合奶昔与烘焙': 'Peel and slice; suitable for smoothies and baking', '未熟时常温催熟': 'Ripen at room temperature',
  '脆响的一口，像把清晨的风也咬进了果香里。': 'A crisp bite with a fresh, fruity aroma.',
  '可鲜食、烤苹果或加入沙拉。': 'Ideas: eat fresh, bake or add to salads.', '与叶菜分开放置': 'Store separately from leafy greens', '切片后更适合烘焙': 'Slice first; best used for baking', '避光通风': 'Keep ventilated and away from light',
  '一缕一缕，最懂得把汤汁和家常的香气牵在一起。': 'Noodles bring together broth, sauces and familiar home flavours.',
  '可做葱油拌面、汤面或番茄意面。': 'Ideas: scallion-oil noodles, noodle soup or tomato pasta.',
  '干面通常无需冷藏': 'Dry noodles usually do not need refrigeration', '干面通常无需冷冻': 'Dry noodles usually do not need freezing',
  '已开封：密封、防潮、避免虫害；包装说明优先': 'Opened: seal, keep dry and protect from pests. Follow the label first.',
  '未开封：以包装最佳食用日期为准；一年仅作缺少包装日期时的提醒占位': 'Sealed: follow the best-before date. One year is only a reminder placeholder when the date is missing.',
  '一粒米很小，却一直是许多家常味道的中心。': 'Rice is a simple foundation for many home-cooked meals.',
  '可煮饭、煲粥或做炒饭。': 'Ideas: steamed rice, congee or fried rice.',
  '干米通常无需冷藏': 'Dry rice usually does not need refrigeration', '干米通常无需冷冻': 'Dry rice usually does not need freezing',
  '已开封：密封、防潮、避虫，并记录开封日': 'Opened: seal, keep dry, protect from pests and record the opening date',
  '未开封：包装日期优先；一年仅作缺少包装日期时的提醒占位': 'Sealed: follow the package date. One year is only a reminder placeholder when it is missing.',
  '土里的甜，经过火候后变得绵软而踏实。': 'Cooking turns earthy sweetness into a soft, comforting bite.',
  '可烤、蒸或切块煮粥。': 'Ideas: bake, steam or dice into congee.',
  '生红薯低温久放易影响品质': 'Prolonged low-temperature storage may affect raw sweet potato quality', '蒸熟后分装冷冻': 'Steam first, then freeze in portions', '阴凉、干燥、通风': 'Cool, dry and ventilated',
  '浓稠的一勺鲜香，最会把蔬菜和肉味轻轻拢在一起。': 'A thick savoury spoonful brings vegetables and meat together.',
  '调味品不作寒热判断': 'No traditional hot/cold classification for condiments', '适合炒蔬菜、腌肉与调制芡汁。': 'Suitable for vegetable stir-fries, marinades and thickened sauces.',
  '已开封：约 4°C 冷藏并保持瓶口清洁；包装若写明更短期限，以包装为准': 'Opened: refrigerate around 4°C and keep the bottle opening clean. Follow any shorter period on the label.',
  '常见品牌开封冷藏建议约 1–6 个月；FreshLoop 默认采用保守的 30 天提醒': 'Common brands suggest about 1–6 months refrigerated after opening. FreshLoop defaults to a conservative 30-day reminder.',
  '不建议冷冻，质地可能改变且玻璃瓶可能破裂': 'Freezing is not recommended: texture may change and glass bottles may crack',
  '已开封：常见品牌要求冷藏，不把常温与冷藏套成同一期限': 'Opened: common brands require refrigeration. Room-temperature and refrigerated periods are not interchangeable.',
  '未开封通常按包装要求常温储存，无需占用冷藏空间': 'Sealed bottles usually stay at room temperature as labelled; refrigeration is generally unnecessary',
  '未开封：可按包装条件常温保存；请优先录入瓶身最佳食用日期': 'Sealed: store at room temperature if permitted by the label. Enter the bottle’s best-before date first.',
  '一小勺酱香，常常就是家常菜的底色。': 'A small spoonful adds a familiar savoury base to home cooking.',
  '适合炒菜、腌肉与调制蘸汁。': 'Suitable for stir-fries, marinades and dipping sauces.',
  '已开封普通瓶：建议冷藏并在 90 天内优先用完；包装说明优先': 'Opened standard bottle: refrigerate and aim to use within 90 days. Follow the label first.',
  '无需冷冻': 'Freezing is unnecessary',
  '已开封普通瓶：常温仅作 30 天保守品质提醒；特殊密封瓶可按包装标注延长': 'Opened standard bottle: 30 days at room temperature is a conservative quality reminder only. Special sealed dispensers may have different labelled periods.',
  '未开封通常按包装要求常温储存': 'Unopened bottles are usually stored at room temperature as labelled',
  '未开封：按包装最佳食用日期；一年仅作缺少包装日期时的提醒占位': 'Sealed: follow the best-before date. One year is only a placeholder reminder when it is missing.',
  '看似安静的一滴油，会把香气从锅底慢慢托起来。': 'A little oil carries aromas through the pan.',
  '不同油脂传统属性不一': 'Traditional food-culture descriptions vary by oil type', '按烟点选择凉拌、煎炒或烘焙。': 'Choose oil for dressing, frying or baking according to its smoke point.',
  '多数食用油无需冷藏': 'Most cooking oils do not need refrigeration',
  '已开封：密封、避光、远离炉火，并留意哈喇味': 'Opened: seal, keep away from light and stove heat, and watch for rancid odours',
  '谷物压成轻巧的一块，把忙碌时刻稳稳接住。': 'A compact grain bar for a busy moment.',
  '加工食品不作寒热判断': 'No traditional hot/cold classification for processed foods', '可直接食用，或切碎撒在酸奶上。': 'Eat as is or crumble over yogurt.',
  '通常无需冷藏': 'Refrigeration is usually unnecessary', '通常无需冷冻': 'Freezing is usually unnecessary', '密封防潮，以包装日期为准': 'Seal and keep dry; follow the package date',
  '一点翠绿落在热菜上，香气就有了醒目的句号。': 'A little green garnish adds a bright aromatic finish.',
  '可做葱油、蛋饼或汤面点缀。': 'Ideas: scallion oil, egg pancakes or noodle-soup garnish.',
  '吸湿包裹后冷藏': 'Wrap in absorbent material and refrigerate', '切碎后冷冻作调味': 'Chop and freeze for seasoning',
  '它从产地来到厨房，正等待你为它安排合适的一餐。': 'Ready for a suitable place in your next meal.',
  '暂无可靠的传统食养归类': 'No reliable traditional food-culture classification available',
  '可按食材状态与个人口味灵活安排。': 'Choose a use based on its condition and your preferences.',
  '仅作短期占位；需要具体品种才能给出更准确期限': 'Short-term placeholder only. Specify the variety for more accurate guidance.',
  '不同蔬菜对焯水、切分和冷冻的要求差异很大，请补充具体品种': 'Blanching, cutting and freezing requirements vary by vegetable. Specify the variety.',
  '仅作一般短期参考': 'General short-term reference only',
  '仅作成熟水果的短期占位；具体品种与成熟度优先': 'Short-term placeholder for ripe fruit only. Variety and ripeness take priority.',
  '需要具体品种与预处理方式，不能统一套用期限': 'Specify the variety and preparation. A single universal period cannot be applied.',
  '未熟水果可短期常温，具体品种优先': 'Unripe fruit may be kept briefly at room temperature, depending on the variety',
  '这是保守占位；请补充具体部位、是否绞碎和包装日期': 'Conservative placeholder. Specify the cut, whether ground, and the package date.',
  '肉类与海鲜不能使用统一期限，请补充品种、形态和包装状态': 'Meat and seafood do not share a universal period. Specify type, form and package state.',
  '生鲜肉与海鲜不可常温久放': 'Do not leave raw meat or seafood at room temperature for extended periods',
  '视具体主食与包装说明': 'Depends on the staple and its package instructions',
  '开封后密封防潮；具体品种和包装日期优先': 'Seal and keep dry after opening. The specific food and package date take priority.',
  '未开封：请优先录入包装最佳食用日期': 'Sealed: enter the package best-before date first',
  '开封后视具体配方和包装说明': 'After opening, follow the specific formulation and label',
  '避光密封；包装说明优先': 'Seal and keep away from light. Follow the label first.',
  '需要识别具体品类或查看包装说明': 'Identify the specific food or consult the package instructions',
  '资料不足，不自动推断可冷冻': 'Insufficient information to recommend freezing',
  '资料不足，请查看包装储存说明': 'Insufficient information. Check the package storage instructions.'
};
